function out = fun(~,y,kappa,beta,const,baseT,baseTdash)
    out(1) = y(2);
    out(2) = ( -( (2*kappa*baseTdash)/((beta^2)*(baseT^3)) )*y(2) ...
        + ( (2*kappa)/((beta^2)*(baseT^2)) ) )/( 2*kappa + ...
        baseT^(-1)*const*((baseTdash)/(2*kappa*baseT)) );